DROP DATABASE IF EXISTS `ARPICO_USER_MANAGEMENT`;

CREATE DATABASE `ARPICO_USER_MANAGEMENT`;

USE `ARPICO_USER_MANAGEMENT`;

DROP TABLE IF EXISTS `ROLE`;

CREATE TABLE `ROLE` (
  `ROLE_ID` varchar(45) NOT NULL,
  `ROLE_DESCRIPTION` varchar(500) DEFAULT NULL,
  `IS_ENABELED` tinyint(1) DEFAULT '1',
  `CREATED_TIME` timestamp NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(45) NOT NULL,
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `PERMISSION`;

CREATE TABLE `PERMISSION` (
  `PERMISSION_ID` varchar(45) NOT NULL,
  `PERMISSION_DESCRIPTION` varchar(500) DEFAULT NULL,
  `PERMISSION_METHOD` varchar(500) DEFAULT NULL,
  `HREF` varchar(300) DEFAULT NULL,
  `IS_ENABELED` tinyint(1) DEFAULT '1',
  `CREATED_TIME` timestamp NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(45) NOT NULL,
  PRIMARY KEY (`PERMISSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `MENU`;

CREATE TABLE `MENU` (
  `MENU_ID` varchar(45) NOT NULL,
  `MENU` varchar(200) DEFAULT NULL,
  `MENU_DESCRIPTION` varchar(500) DEFAULT NULL,
  `HREF` varchar(300) DEFAULT NULL,
  `ICON` varchar(200) DEFAULT NULL,
  `PARENT` int(45) DEFAULT NULL,
  `LEVEL` int(2) DEFAULT NULL,
  `IS_ENABELED` tinyint(1) DEFAULT '1',
  `CREATED_TIME` timestamp NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(45) NOT NULL,
  PRIMARY KEY (`MENU_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `ROLE_PERMISSION`;

CREATE TABLE `ROLE_PERMISSION` (
  `ROLE_PERMISSION_ID` varchar(45) NOT NULL,
  `ROLE_ID` varchar(45) NOT NULL,
  `PERMISSION_ID` varchar(45) NOT NULL,
  `IS_ENABELED` tinyint(1) DEFAULT '1',
  `CREATED_TIME` timestamp NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(45) NOT NULL,
  PRIMARY KEY (`ROLE_PERMISSION_ID`),
  FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE`(`ROLE_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`PERMISSION_ID`) REFERENCES `PERMISSION`(`PERMISSION_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `ROLE_MENU`;

CREATE TABLE `ROLE_MENU` (
  `ROLE_MENU_ID` varchar(45) NOT NULL,
  `ROLE_ID` varchar(45) NOT NULL,
  `MENU_ID` varchar(45) NOT NULL,
  `IS_ENABELED` tinyint(1) DEFAULT '1',
  `CREATED_TIME` timestamp NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(45) NOT NULL,
  PRIMARY KEY (`ROLE_MENU_ID`),
  FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE`(`ROLE_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`MENU_ID`) REFERENCES `MENU`(`MENU_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `SYSUSER`;

CREATE TABLE `SYSUSER` (
  `SYSUSER_ID` varchar(45) NOT NULL,
  `USER_SALUTION` varchar(100) NOT NULL,
  `USER_FIRST_NAME` varchar(100) NOT NULL,
  `USER_LAST_NAME` varchar(100) NOT NULL,
  `USER_NIC` varchar(20) NOT NULL,
  `USER_PASSPORT` varchar(20) NOT NULL,
  `USER_ADDRESS_1` varchar(100) NOT NULL,
  `USER_ADDRESS_2` varchar(100) DEFAULT NULL,
  `USER_ADDRESS_3` varchar(100) DEFAULT NULL,
  `USER_MOBILE_NUMBER` varchar(20) NOT NULL,
  `USER_TELEPHONE_NUMBER` varchar(20) DEFAULT NULL,
  `USER_EMAIL` varchar(200) DEFAULT NULL,
  `USER_CODE` varchar(100) NOT NULL,
  `USER_EMPLOYEE_NO` varchar(100) NOT NULL,
  `USER_NAME` varchar(100) NOT NULL,
  `USER_PASSWORD` varchar(100) NOT NULL,
  `IS_ENABELED` tinyint(1) DEFAULT '1',
  `CREATED_TIME` timestamp NOT NULL ,
  `CREATED_BY` varchar(45) NOT NULL,
  `UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(45) NOT NULL,
  PRIMARY KEY (`SYSUSER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `SYSUSER_ROLE`;

CREATE TABLE `SYSUSER_ROLE` (
  `SYSUSER_ROLE_ID` varchar(45) NOT NULL,
  `ROLE_ID` varchar(45) NOT NULL,
  `SYSUSER_ID` varchar(45) NOT NULL,
  `IS_ENABELED` tinyint(1) DEFAULT '1',
  `CREATED_TIME` timestamp NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(45) NOT NULL,
  PRIMARY KEY (`SYSUSER_ROLE_ID`),
  FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE`(`ROLE_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`SYSUSER_ID`) REFERENCES `SYSUSER`(`SYSUSER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `SBU`;

CREATE TABLE `SBU` (
  `SBU_ID` varchar(45) NOT NULL,
  `SBU_NAME` varchar(200) NOT NULL,
  `SBU_SHORT_NAME` varchar(50) NOT NULL,
  `IS_ENABELED` tinyint(1) DEFAULT '1',
  `CREATED_TIME` timestamp NOT NULL ,
  `CREATED_BY` varchar(45) NOT NULL,
  `UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(45) NOT NULL,
  PRIMARY KEY (`SBU_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `SUB_SBU`;

CREATE TABLE `SUB_SBU` (
  `SUB_SBU_ID` varchar(45) NOT NULL,
  `SBU_ID` varchar(45) NOT NULL,
  `SUB_SBU_NAME` varchar(200) NOT NULL,
  `SUB_SBU_SHORT_NAME` varchar(50) NOT NULL,
  `SUB_SBU_ADDRESS_1` varchar(100) NOT NULL,
  `SUB_SBU_ADDRESS_2` varchar(100) DEFAULT NULL,
  `SUB_SBU_ADDRESS_3` varchar(100) DEFAULT NULL,
  `SUB_SBU_CITY` varchar(100) DEFAULT NULL,
  `SUB_SBU_EMAIL` varchar(200) DEFAULT NULL,
  `SUB_SBU_FAX` varchar(100) NOT NULL,
  `SUB_SBU_TAX_NO` varchar(100) NOT NULL,
  `SUB_SBU_TELE` varchar(100) NOT NULL,
  `SUB_SBU_TELE_X` varchar(100) NOT NULL,
  `IS_ENABELED` tinyint(1) DEFAULT '1',
  `CREATED_TIME` timestamp NOT NULL ,
  `CREATED_BY` varchar(45) NOT NULL,
  `UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(45) NOT NULL,
  PRIMARY KEY (`SUB_SBU_ID`),
  FOREIGN KEY (`SBU_ID`) REFERENCES `SBU`(`SBU_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `LOCATION`;

CREATE TABLE `LOCATION` (
  `LOCATION_ID` varchar(45) NOT NULL,
  `SUB_SBU_ID` varchar(45) NOT NULL,
  `LOCATION_NAME` varchar(200) NOT NULL,
  `LOCATION_SHORT_NAME` varchar(50) NOT NULL,
  `LOCATION_ADDRESS_1` varchar(100) NOT NULL,
  `LOCATION_ADDRESS_2` varchar(100) DEFAULT NULL,
  `LOCATION_ADDRESS_3` varchar(100) DEFAULT NULL,
  `LOCATION_CITY` varchar(100) DEFAULT NULL,
  `LOCATION_EMAIL` varchar(200) DEFAULT NULL,
  `LOCATION_FAX` varchar(100) NOT NULL,
  `LOCATION_TELE` varchar(100) NOT NULL,
  `LOCATION_TELE_X` varchar(100) NOT NULL,
  `IS_ENABELED` tinyint(1) DEFAULT '1',
  `CREATED_TIME` timestamp NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(45) NOT NULL,
  PRIMARY KEY (`LOCATION_ID`),
  FOREIGN KEY (`SUB_SBU_ID`) REFERENCES `SUB_SBU`(`SUB_SBU_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `SUB_SBU_SYSUSER`;

CREATE TABLE `SUB_SBU_SYSUSER` (
  `SUB_SBU_SYSUSER_ID` varchar(45) NOT NULL,
  `SUB_SBU_ID` varchar(45) NOT NULL,
  `SYSUSER_ID` varchar(45) NOT NULL,
  `IS_ENABELED` tinyint(1) DEFAULT '1',
  `CREATED_TIME` timestamp NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(45) NOT NULL,
  PRIMARY KEY (`SUB_SBU_SYSUSER_ID`),
  FOREIGN KEY (`SUB_SBU_ID`) REFERENCES `SUB_SBU`(`SUB_SBU_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`SYSUSER_ID`) REFERENCES `SYSUSER`(`SYSUSER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `SUB_SBU_SYSUSER_PERMISSION`;

CREATE TABLE `SUB_SBU_SYSUSER_PERMISSION` (
  `SUB_SBU_SYSUSER_PERMISSION_ID` varchar(45) NOT NULL,
  `SUB_SBU_SYSUSER_ID` varchar(45) NOT NULL,
  `PERMISSION_ID` varchar(45) NOT NULL,
  `IS_ENABELED` tinyint(1) DEFAULT '1',
  `CREATED_TIME` timestamp NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(45) NOT NULL,
  PRIMARY KEY (`SUB_SBU_SYSUSER_PERMISSION_ID`),
  FOREIGN KEY (`SUB_SBU_SYSUSER_ID`) REFERENCES `SUB_SBU_SYSUSER`(`SUB_SBU_SYSUSER_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`PERMISSION_ID`) REFERENCES `PERMISSION`(`PERMISSION_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `SUB_SBU_SYSUSER_MENU`;

CREATE TABLE `SUB_SBU_SYSUSER_MENU` (
  `SUB_SBU_SYSUSER_MENU_ID` varchar(45) NOT NULL,
  `SUB_SBU_SYSUSER_ID` varchar(45) NOT NULL,
  `MENU_ID` varchar(45) NOT NULL,
  `IS_ENABELED` tinyint(1) DEFAULT '1',
  `CREATED_TIME` timestamp NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(45) NOT NULL,
  PRIMARY KEY (`SUB_SBU_SYSUSER_MENU_ID`),
  FOREIGN KEY (`SUB_SBU_SYSUSER_ID`) REFERENCES `SUB_SBU_SYSUSER`(`SUB_SBU_SYSUSER_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`MENU_ID`) REFERENCES `MENU`(`MENU_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `ACCESS_CONTROL`;

CREATE TABLE `ACCESS_CONTROL` (
  `ACCESS_CONTROL_ID` varchar(45) NOT NULL,
  `ACCESS_CONTROL_SHORT_NAME` varchar(50) NOT NULL,
  `ACCESS_CONTROL_NAME` varchar(200) NOT NULL,
  `ACCESS_CONTROL_DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ENABELED` tinyint(1) DEFAULT '1',
  `CREATED_TIME` timestamp NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(45) NOT NULL,
  PRIMARY KEY (`ACCESS_CONTROL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `SYSUSER_ACCESS_CONTROL`;

CREATE TABLE `SYSUSER_ACCESS_CONTROL` (
  `SYSUSER_ACCESS_CONTROL_ID` varchar(45) NOT NULL,
  `ACCESS_CONTROL_ID` varchar(45) NOT NULL,
  `SYSUSER_ID` varchar(45) NOT NULL,
  `IS_ENABELED` tinyint(1) DEFAULT '1',
  `CREATED_TIME` timestamp NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(45) NOT NULL,
  PRIMARY KEY (`SYSUSER_ACCESS_CONTROL_ID`),
  FOREIGN KEY (`ACCESS_CONTROL_ID`) REFERENCES `ACCESS_CONTROL`(`ACCESS_CONTROL_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`SYSUSER_ID`) REFERENCES `SYSUSER`(`SYSUSER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


